[package]
name = "db"
version = "0.1.0"
authors = ["wangzhf <zhifengtech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

diesel = "1.4.3"
dotenv = "0.15.0"

